version: 2.1
jobs:
  say-hello:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "brew install --cask docker; open -a /Applications/Docker.app; sleep 60; docker run ubuntu:latest lscpu"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
